"""financial_institutions_portfolios

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-05 16:09:48.174771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_institutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reporting_currency', sa.String(length=3), nullable=False),
    sa.Column('tenant_key', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key')
    )
    op.create_table('institution_borrowers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=100), nullable=False),
    sa.Column('consent_status', sa.String(length=20), nullable=False),
    sa.Column('consent_scope_json', sa.JSON(), nullable=True),
    sa.Column('consent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("consent_status IN ('pending', 'active', 'revoked', 'expired')", name='ck_institution_borrowers_consent_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_institution_id', 'external_customer_id', name='uq_institution_borrowers_institution_external_id')
    )
    op.create_table('institution_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'analyst', 'reviewer', 'approver', 'viewer')", name='ck_institution_users_role'),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_institution_users_institution_user', 'institution_users', ['financial_institution_id', 'user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reporting_year', sa.SmallInteger(), nullable=False),
    sa.Column('reporting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporting_currency', sa.String(length=3), nullable=False),
    sa.Column('scope_mode', sa.String(length=30), nullable=False),
    sa.Column('total_relevant_outstanding', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('reporting_date_events_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_portfolio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope_mode IN ('supported_business_loans', 'full_institution')", name='ck_portfolios_scope_mode'),
    sa.CheckConstraint("status IN ('draft', 'calculated', 'reviewed', 'approved', 'superseded')", name='ck_portfolios_status'),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_institution_year', 'portfolios', ['financial_institution_id', 'reporting_year'], unique=False)
    # 주의: ix_unit_prices_fuel_year_month 는 이 revision과 무관한 기존(0001 이전) 테이블의 인덱스.
    # 0001 baseline이 no-op이라 autogenerate가 "누락"으로 오탐지했으므로 제외했다 — Supabase에 이미 존재함.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolios_institution_year', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_institution_users_institution_user', table_name='institution_users')
    op.drop_table('institution_users')
    op.drop_table('institution_borrowers')
    op.drop_table('financial_institutions')
    # ### end Alembic commands ###
