"""organizational_boundary_inventory

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-05 16:11:21.633445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_boundaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.SmallInteger(), nullable=False),
    sa.Column('boundary_type', sa.String(length=30), nullable=False),
    sa.Column('consolidation_scope', sa.String(length=20), nullable=False),
    sa.Column('included_entities_json', sa.JSON(), nullable=True),
    sa.Column('excluded_entities_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("boundary_type IN ('operational_control', 'financial_control', 'equity_share')", name='ck_org_boundaries_boundary_type'),
    sa.CheckConstraint("consolidation_scope IN ('consolidated', 'separate')", name='ck_org_boundaries_consolidation_scope'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_boundaries_company_year', 'organizational_boundaries', ['company_id', 'reporting_year'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_documents_company', 'source_documents', ['company_id'], unique=False)
    op.create_index('ix_source_documents_file_hash', 'source_documents', ['file_hash'], unique=False)
    op.create_table('borrower_emission_inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.SmallInteger(), nullable=False),
    sa.Column('organizational_boundary_id', sa.Integer(), nullable=False),
    sa.Column('scope_group', sa.String(length=10), nullable=False),
    sa.Column('scope2_method', sa.String(length=20), nullable=True),
    sa.Column('scope3_status', sa.String(length=20), nullable=True),
    sa.Column('emission_tco2e', sa.Float(), nullable=True),
    sa.Column('calculation_method_summary', sa.Text(), nullable=True),
    sa.Column('gwp_version', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=True),
    sa.Column('completeness_pct', sa.Float(), nullable=True),
    sa.Column('candidate_quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('candidate_quality_rule_id', sa.Integer(), nullable=True),
    sa.Column('limitations_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_inventory_id', sa.Integer(), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope2_method IS NULL OR scope2_method IN ('location_based', 'market_based')", name='ck_inventories_scope2_method'),
    sa.CheckConstraint("scope3_status IS NULL OR scope3_status IN ('reported', 'estimated', 'not_reported', 'not_calculated', 'not_applicable')", name='ck_inventories_scope3_status'),
    sa.CheckConstraint("scope_group IN ('scope_1', 'scope_2', 'scope_3')", name='ck_inventories_scope_group'),
    sa.CheckConstraint("status IN ('draft', 'calculated', 'reviewed', 'approved', 'superseded')", name='ck_inventories_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.ForeignKeyConstraint(['organizational_boundary_id'], ['organizational_boundaries.id'], ),
    sa.ForeignKeyConstraint(['supersedes_inventory_id'], ['borrower_emission_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventories_company_year_scope', 'borrower_emission_inventories', ['company_id', 'reporting_year', 'scope_group'], unique=False)
    op.create_table('inventory_gas_emissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('gas_type', sa.String(length=10), nullable=False),
    sa.Column('emission_mass', sa.Float(), nullable=True),
    sa.Column('mass_unit', sa.String(length=20), nullable=True),
    sa.Column('gwp_value', sa.Float(), nullable=True),
    sa.Column('gwp_version', sa.String(length=20), nullable=True),
    sa.Column('emission_co2e', sa.Float(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("gas_type IN ('CO2', 'CH4', 'N2O', 'HFCs', 'PFCs', 'SF6', 'NF3')", name='ck_gas_emissions_gas_type'),
    sa.ForeignKeyConstraint(['inventory_id'], ['borrower_emission_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gas_emissions_inventory', 'inventory_gas_emissions', ['inventory_id'], unique=False)
    # 주의: ix_unit_prices_fuel_year_month 오탐지 제외 (0002와 동일 사유 — 0001 baseline no-op)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gas_emissions_inventory', table_name='inventory_gas_emissions')
    op.drop_table('inventory_gas_emissions')
    op.drop_index('ix_inventories_company_year_scope', table_name='borrower_emission_inventories')
    op.drop_table('borrower_emission_inventories')
    op.drop_index('ix_source_documents_file_hash', table_name='source_documents')
    op.drop_index('ix_source_documents_company', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_org_boundaries_company_year', table_name='organizational_boundaries')
    op.drop_table('organizational_boundaries')
    # ### end Alembic commands ###
