"""exposure_financials_fx

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-05 16:12:47.511906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rate_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rate_type IN ('closing', 'average', 'policy_defined')", name='ck_fx_rates_rate_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fx_rates_pair_date', 'fx_rates', ['base_currency', 'quote_currency', 'rate_date'], unique=False)
    op.create_table('borrower_financials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.SmallInteger(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('debt_definition', sa.Text(), nullable=True),
    sa.Column('consolidation_scope', sa.String(length=20), nullable=True),
    sa.Column('included_entities_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borrower_financials_company_year', 'borrower_financials', ['company_id', 'financial_year'], unique=False)
    op.create_table('business_loan_exposures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_exposure_id', sa.String(length=100), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reporting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('company_type', sa.String(length=30), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('source_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'external_exposure_id', name='uq_business_loan_exposures_portfolio_external_id')
    )
    op.create_index('ix_business_loan_exposures_company', 'business_loan_exposures', ['company_id'], unique=False)
    # 주의: ix_unit_prices_fuel_year_month 오탐지 제외 (0002/0003과 동일 사유)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_loan_exposures_company', table_name='business_loan_exposures')
    op.drop_table('business_loan_exposures')
    op.drop_index('ix_borrower_financials_company_year', table_name='borrower_financials')
    op.drop_table('borrower_financials')
    op.drop_index('ix_fx_rates_pair_date', table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
