"""voucher_classification_fk_columns

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-05 16:14:20.256471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. 기존 vouchers/classifications 컬럼 추가 — 전부 nullable, 데이터 변경 없음.
    백필(institution_borrowers/financial_institutions 값 채우기)은 0006에서 별도 처리한다."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('classification_method', sa.String(length=10), nullable=True))
    op.add_column('classifications', sa.Column('activity_data_method', sa.String(length=30), nullable=True))
    op.add_column('classifications', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.add_column('classifications', sa.Column('quantity_source', sa.String(length=20), nullable=True))
    op.add_column('classifications', sa.Column('factor_id', sa.Integer(), nullable=True))
    op.add_column('classifications', sa.Column('factor_version', sa.String(length=20), nullable=True))
    op.add_column('classifications', sa.Column('data_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classifications', sa.Column('data_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classifications', sa.Column('calculation_warning', sa.JSON(), nullable=True))
    op.create_foreign_key('fk_classifications_factor_id', 'classifications', 'emission_factors', ['factor_id'], ['id'])
    op.create_foreign_key('fk_classifications_source_document_id', 'classifications', 'source_documents', ['source_document_id'], ['id'])
    op.create_check_constraint('ck_classifications_activity_data_method', 'classifications', "activity_data_method IS NULL OR activity_data_method IN ('reported_quantity', 'invoice_quantity', 'spend_converted', 'economic_estimate', 'industry_estimate')")
    op.create_check_constraint('ck_classifications_classification_method', 'classifications', "classification_method IS NULL OR classification_method IN ('rule', 'llm', 'manual')")
    # 주의: ix_unit_prices_fuel_year_month 오탐지 제외 (0002~0004와 동일 사유)
    op.add_column('vouchers', sa.Column('financial_institution_id', sa.Integer(), nullable=True))
    op.add_column('vouchers', sa.Column('institution_borrower_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_vouchers_institution_borrower_id', 'vouchers', 'institution_borrowers', ['institution_borrower_id'], ['id'])
    op.create_foreign_key('fk_vouchers_financial_institution_id', 'vouchers', 'financial_institutions', ['financial_institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vouchers_institution_borrower_id', 'vouchers', type_='foreignkey')
    op.drop_constraint('fk_vouchers_financial_institution_id', 'vouchers', type_='foreignkey')
    op.drop_column('vouchers', 'institution_borrower_id')
    op.drop_column('vouchers', 'financial_institution_id')
    op.drop_constraint('ck_classifications_classification_method', 'classifications', type_='check')
    op.drop_constraint('ck_classifications_activity_data_method', 'classifications', type_='check')
    op.drop_constraint('fk_classifications_factor_id', 'classifications', type_='foreignkey')
    op.drop_constraint('fk_classifications_source_document_id', 'classifications', type_='foreignkey')
    op.drop_column('classifications', 'calculation_warning')
    op.drop_column('classifications', 'data_period_end')
    op.drop_column('classifications', 'data_period_start')
    op.drop_column('classifications', 'factor_version')
    op.drop_column('classifications', 'factor_id')
    op.drop_column('classifications', 'quantity_source')
    op.drop_column('classifications', 'source_document_id')
    op.drop_column('classifications', 'activity_data_method')
    op.drop_column('classifications', 'classification_method')
    # ### end Alembic commands ###
